from copy import deepcopy


RESTAURANT_COORDS = {"lat": 21.0260, "lng": 105.8550}
DELIVERY_ROUTE = [
    {"lat": 21.0260, "lng": 105.8550, "detail": "Tai xe dang nhan don tai nha hang Huong Viet."},
    {"lat": 21.0270, "lng": 105.8540, "detail": "Tai xe di qua khu vuc Hoan Kiem."},
    {"lat": 21.0285, "lng": 105.8521, "detail": "Tai xe dang di doc Dinh Tien Hoang."},
    {"lat": 21.0295, "lng": 105.8505, "detail": "Tai xe di qua nga tu Trang Tien - Hang Khay."},
    {"lat": 21.0312, "lng": 105.8495, "detail": "Tai xe dang re vao Lo Su."},
    {"lat": 21.0325, "lng": 105.8480, "detail": "Tai xe da vao pho co Hang Bac."},
    {"lat": 21.0335, "lng": 105.8465, "detail": "Tai xe dang den gan dia chi khach hang."},
    {"lat": 21.0338, "lng": 105.8460, "detail": "Tai xe da den noi va dang giao hang."},
]

BASE_DISHES = [
    {
        "id": "dish-1",
        "name": "Pho Bo Huong Viet",
        "description": "Nuoc dung bo dam da, banh pho tuoi va thit bo thai mong.",
        "price": 120000,
        "image": "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.9,
        "ingredients": ["Banh pho", "Thit bo", "Nuoc dung", "Que hoi"],
        "nutrition": {"calories": 450, "protein": "32g", "carbs": "55g", "fat": "12g"},
    },
    {
        "id": "dish-2",
        "name": "Bun Cha Ha Noi",
        "description": "Bun cha nuong than hoa, rau song va nuoc mam chua ngot.",
        "price": 95000,
        "image": "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.8,
        "ingredients": ["Bun", "Cha nuong", "Rau song", "Nuoc mam"],
        "nutrition": {"calories": 512, "protein": "28g", "carbs": "60g", "fat": "16g"},
    },
    {
        "id": "dish-3",
        "name": "Nem Cuon Tom Thit",
        "description": "Nem cuon tom thit tuoi an kem tuong den dau phong.",
        "price": 60000,
        "image": "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500&auto=format&fit=crop&q=60",
        "category": "starter",
        "rating": 4.7,
        "ingredients": ["Tom", "Thit heo", "Banh trang", "Rau song"],
        "nutrition": {"calories": 240, "protein": "14g", "carbs": "28g", "fat": "6g"},
    },
    {
        "id": "dish-4",
        "name": "Cha Ca La Vong",
        "description": "Ca lang uop nghe va thi la, phuc vu nong tai ban.",
        "price": 180000,
        "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.9,
        "ingredients": ["Ca lang", "Thi la", "Hanh hoa", "Mam tom"],
        "nutrition": {"calories": 410, "protein": "35g", "carbs": "12g", "fat": "22g"},
    },
    {
        "id": "dish-5",
        "name": "Ca Phe Trung",
        "description": "Ca phe trung beo min, phuc vu nong kieu Ha Noi.",
        "price": 50000,
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=60",
        "category": "drink",
        "rating": 4.9,
        "ingredients": ["Ca phe", "Long do trung", "Sua dac"],
        "nutrition": {"calories": 230, "protein": "6g", "carbs": "24g", "fat": "10g"},
    },
    {
        "id": "dish-6",
        "name": "Tra Sen Tay Ho",
        "description": "Tra sen thanh mat, huong vi nhe va thanh tao.",
        "price": 40000,
        "image": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60",
        "category": "drink",
        "rating": 4.8,
        "ingredients": ["Tra xanh", "Sen"],
        "nutrition": {"calories": 5, "protein": "0g", "carbs": "1g", "fat": "0g"},
    },
    {
        "id": "dish-7",
        "name": "Bun Bo Hue Song Huong",
        "description": "Nuoc dung cay nhe, sa thom, bun tron dai va chan gio ham mem.",
        "price": 110000,
        "image": "https://images.unsplash.com/photo-1555126634-323283e090fa?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.9,
        "ingredients": ["Bun", "Bo bap", "Cha cua", "Sa", "Mam ruoc"],
        "nutrition": {"calories": 540, "protein": "30g", "carbs": "62g", "fat": "18g"},
    },
    {
        "id": "dish-8",
        "name": "Com Tam Suon Bi Cha",
        "description": "Com tam deo thom, suon nuong mat ong, bi heo va cha trung hap.",
        "price": 98000,
        "image": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.8,
        "ingredients": ["Com tam", "Suon nuong", "Bi heo", "Cha trung"],
        "nutrition": {"calories": 610, "protein": "29g", "carbs": "68g", "fat": "21g"},
    },
    {
        "id": "dish-9",
        "name": "Goi Ngo Sen Tom Thit",
        "description": "Ngo sen gion mat tron tom thit, rau rom va nuoc mam cham chua ngot.",
        "price": 89000,
        "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60",
        "category": "starter",
        "rating": 4.7,
        "ingredients": ["Ngo sen", "Tom", "Thit ba chi", "Rau rom"],
        "nutrition": {"calories": 260, "protein": "16g", "carbs": "22g", "fat": "8g"},
    },
    {
        "id": "dish-10",
        "name": "Banh Xeo Mien Tay",
        "description": "Vo banh vang gion, nhan tom thit gia do, cuon rau song dam vi.",
        "price": 92000,
        "image": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500&auto=format&fit=crop&q=60",
        "category": "starter",
        "rating": 4.8,
        "ingredients": ["Bot gao", "Tom", "Thit", "Gia do", "Rau song"],
        "nutrition": {"calories": 380, "protein": "18g", "carbs": "36g", "fat": "16g"},
    },
    {
        "id": "dish-11",
        "name": "Lau Thai Hai San",
        "description": "Nuoc lau chua cay, hai san tuoi, nam va rau an kem phong phu.",
        "price": 289000,
        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.9,
        "ingredients": ["Tom", "Muc", "Ngao", "Nam", "Sa ot"],
        "nutrition": {"calories": 720, "protein": "48g", "carbs": "40g", "fat": "28g"},
    },
    {
        "id": "dish-12",
        "name": "Ga Nuong La Chanh",
        "description": "Ga nuong da gion, huong la chanh va muoi tieu chanh dac trung.",
        "price": 165000,
        "image": "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.8,
        "ingredients": ["Ga ta", "La chanh", "Muoi tieu", "Mat ong"],
        "nutrition": {"calories": 530, "protein": "42g", "carbs": "8g", "fat": "24g"},
    },
    {
        "id": "dish-13",
        "name": "Che Khuc Bach Vai",
        "description": "Khuc bach mem mat, vai tuoi, hanh nhan rang va nuoc duong thanh.",
        "price": 52000,
        "image": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=60",
        "category": "dessert",
        "rating": 4.7,
        "ingredients": ["Sua tuoi", "Gelatin", "Vai", "Hanh nhan"],
        "nutrition": {"calories": 210, "protein": "5g", "carbs": "24g", "fat": "10g"},
    },
    {
        "id": "dish-14",
        "name": "Banh Flan Caramel",
        "description": "Banh flan mem min, thom trung sua va lop caramel dang nhe.",
        "price": 38000,
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=60",
        "category": "dessert",
        "rating": 4.6,
        "ingredients": ["Trung ga", "Sua", "Duong caramel"],
        "nutrition": {"calories": 190, "protein": "6g", "carbs": "20g", "fat": "9g"},
    },
    {
        "id": "dish-15",
        "name": "Nuoc Ep Cam Xa",
        "description": "Cam tuoi ep lanh ket hop xa, giai nhiet va de uong.",
        "price": 45000,
        "image": "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&auto=format&fit=crop&q=60",
        "category": "drink",
        "rating": 4.7,
        "ingredients": ["Cam tuoi", "Xa", "Da"],
        "nutrition": {"calories": 95, "protein": "1g", "carbs": "22g", "fat": "0g"},
    },
    {
        "id": "dish-16",
        "name": "Sinh To Bo Dua",
        "description": "Bo chin xay cung dua non va sua, beo min va no lau.",
        "price": 55000,
        "image": "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=500&auto=format&fit=crop&q=60",
        "category": "drink",
        "rating": 4.8,
        "ingredients": ["Bo", "Dua non", "Sua dac"],
        "nutrition": {"calories": 260, "protein": "4g", "carbs": "28g", "fat": "14g"},
    },
    {
        "id": "dish-17",
        "name": "Banh Cuon Nong Thanh Tri",
        "description": "Banh cuon mong mem, nhan thit moc nhi, an kem cha que nong.",
        "price": 72000,
        "image": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=60",
        "category": "starter",
        "rating": 4.8,
        "ingredients": ["Bot gao", "Thit xay", "Moc nhi", "Cha que"],
        "nutrition": {"calories": 320, "protein": "15g", "carbs": "42g", "fat": "9g"},
    },
    {
        "id": "dish-18",
        "name": "Mien Luon Nghe An",
        "description": "Mien xao luon gion thom, rau ram va hanh phi day huong vi.",
        "price": 118000,
        "image": "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.8,
        "ingredients": ["Luon", "Mien dong", "Rau ram", "Hanh phi"],
        "nutrition": {"calories": 470, "protein": "27g", "carbs": "44g", "fat": "20g"},
    },
    {
        "id": "dish-19",
        "name": "Mi Quang Tom Thit",
        "description": "Mi quang nghe vang, tom thit dam da, banh trang me va rau song.",
        "price": 105000,
        "image": "https://images.unsplash.com/photo-1625944525533-473f1b3d54b3?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.9,
        "ingredients": ["Mi quang", "Tom", "Thit heo", "Banh trang"],
        "nutrition": {"calories": 520, "protein": "26g", "carbs": "58g", "fat": "18g"},
    },
    {
        "id": "dish-20",
        "name": "Banh Beo Chen Hue",
        "description": "Banh beo mem, tom cha rang va mo hanh thom beo vua du.",
        "price": 68000,
        "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500&auto=format&fit=crop&q=60",
        "category": "starter",
        "rating": 4.7,
        "ingredients": ["Bot gao", "Tom cha", "Mo hanh", "Nuoc mam"],
        "nutrition": {"calories": 250, "protein": "10g", "carbs": "35g", "fat": "8g"},
    },
    {
        "id": "dish-21",
        "name": "Oc Len Xao Dua",
        "description": "Oc len beo thom, nuoc cot dua cay nhe, an kem banh mi nong.",
        "price": 93000,
        "image": "https://images.unsplash.com/photo-1559847844-5315695dadae?w=500&auto=format&fit=crop&q=60",
        "category": "starter",
        "rating": 4.8,
        "ingredients": ["Oc len", "Nuoc cot dua", "Sa", "Ot"],
        "nutrition": {"calories": 340, "protein": "18g", "carbs": "14g", "fat": "21g"},
    },
    {
        "id": "dish-22",
        "name": "Ca Kho To Truyen Thong",
        "description": "Ca kho nuoc mau dua, tieu xanh va nuoc mam nhi, an cung com trang rat bat.",
        "price": 145000,
        "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.9,
        "ingredients": ["Ca basa", "Nuoc mau", "Tieu xanh", "Nuoc mam"],
        "nutrition": {"calories": 430, "protein": "33g", "carbs": "10g", "fat": "25g"},
    },
    {
        "id": "dish-23",
        "name": "Canh Chua Ca Loc",
        "description": "Nuoc canh chua thanh, ca loc tuoi, bac ha va dua gia giu vi Nam Bo.",
        "price": 128000,
        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.7,
        "ingredients": ["Ca loc", "Bac ha", "Ca chua", "Gia do"],
        "nutrition": {"calories": 290, "protein": "24g", "carbs": "16g", "fat": "12g"},
    },
    {
        "id": "dish-24",
        "name": "Bun Rieu Cua Dong",
        "description": "Rieu cua dong beo nhe, ca chua do, dau phu va mam tom tuy chon.",
        "price": 98000,
        "image": "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=500&auto=format&fit=crop&q=60",
        "category": "main",
        "rating": 4.8,
        "ingredients": ["Bun", "Cua dong", "Ca chua", "Dau phu"],
        "nutrition": {"calories": 460, "protein": "22g", "carbs": "56g", "fat": "14g"},
    },
    {
        "id": "dish-25",
        "name": "Sua Chua Nep Cam",
        "description": "Sua chua min mat an cung nep cam deo thom, ngot nhe de ghi nho.",
        "price": 45000,
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=60",
        "category": "dessert",
        "rating": 4.7,
        "ingredients": ["Sua chua", "Nep cam", "Sua dac"],
        "nutrition": {"calories": 220, "protein": "5g", "carbs": "32g", "fat": "8g"},
    },
    {
        "id": "dish-26",
        "name": "Che Troi Nuoc Gung",
        "description": "Vien che deo mem nhan dau xanh, nuoc gung nong thom va me den rang.",
        "price": 42000,
        "image": "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=500&auto=format&fit=crop&q=60",
        "category": "dessert",
        "rating": 4.6,
        "ingredients": ["Bot nep", "Dau xanh", "Gung", "Me den"],
        "nutrition": {"calories": 240, "protein": "4g", "carbs": "42g", "fat": "6g"},
    },
    {
        "id": "dish-27",
        "name": "Tra Tac Xa Chia",
        "description": "Tra tac giai nhiet, them hat chia va mut tac de can bang vi chua ngot.",
        "price": 39000,
        "image": "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=500&auto=format&fit=crop&q=60",
        "category": "drink",
        "rating": 4.7,
        "ingredients": ["Tac", "Hat chia", "Tra", "Mat ong"],
        "nutrition": {"calories": 80, "protein": "1g", "carbs": "19g", "fat": "1g"},
    },
    {
        "id": "dish-28",
        "name": "Nuoc Mia Hat Chia",
        "description": "Nuoc mia lanh ngot tu nhien, them hat chia giup de uong va thanh mat.",
        "price": 35000,
        "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
        "category": "drink",
        "rating": 4.6,
        "ingredients": ["Nuoc mia", "Hat chia", "Tac"],
        "nutrition": {"calories": 110, "protein": "1g", "carbs": "27g", "fat": "0g"},
    },
]

SAMPLE_REVIEWS = [
    {"name": "Tran Anh Tuan", "rating": 5, "text": "Mon an dam vi va phuc vu rat chu dao."},
    {"name": "Pham Minh Thu", "rating": 5, "text": "Do an giao den van nong va dep mat."},
    {"name": "Le Hoang Vy", "rating": 4, "text": "Khong gian va menu deu rat co gu."},
]

DEFAULT_USERS = [
    {
        "username": "khach",
        "password": "123",
        "fullName": "Thuc Khach Ha Noi",
        "phoneNumber": "0911223344",
        "address": "12 Hang Duong, Hoan Kiem, Ha Noi",
        "role": "customer",
        "avatar": "TK",
        "provider": "local",
        "email": "",
    },
    {
        "username": "quan",
        "password": "123",
        "fullName": "Chu Quan Huong Viet",
        "phoneNumber": "0243999999",
        "address": "36 Dinh Tien Hoang, Hoan Kiem, Ha Noi",
        "role": "restaurant",
        "avatar": "HV",
        "provider": "local",
        "email": "",
    },
    {
        "username": "shipper",
        "password": "123",
        "fullName": "Tran Van Dinh",
        "phoneNumber": "0999888777",
        "address": "Trung tam dieu phoi Ha Noi",
        "role": "shipper",
        "avatar": "TD",
        "provider": "local",
        "email": "",
    },
]


def seed_dishes() -> list[dict]:
    dishes = deepcopy(BASE_DISHES)
    for index, dish in enumerate(dishes):
        dish["isAvailable"] = True
        dish["reviews"] = [
            {
                "id": f"rev-{dish['id']}-1",
                "name": SAMPLE_REVIEWS[index % len(SAMPLE_REVIEWS)]["name"],
                "rating": SAMPLE_REVIEWS[index % len(SAMPLE_REVIEWS)]["rating"],
                "text": SAMPLE_REVIEWS[index % len(SAMPLE_REVIEWS)]["text"],
                "date": "2026-06-08",
            },
            {
                "id": f"rev-{dish['id']}-2",
                "name": SAMPLE_REVIEWS[(index + 1) % len(SAMPLE_REVIEWS)]["name"],
                "rating": SAMPLE_REVIEWS[(index + 1) % len(SAMPLE_REVIEWS)]["rating"],
                "text": SAMPLE_REVIEWS[(index + 1) % len(SAMPLE_REVIEWS)]["text"],
                "date": "2026-06-09",
            },
        ]
    return dishes
